import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { cache } from "react";
import { TRPCReactProvider } from "@/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const getHeaders = cache(async () => headers());
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider  headersPromise={getHeaders()}>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
